raw_count_file = "./results/TCGA-LUAD.raw.count.tn.xls"
normalization_count_file = "./results/TCGA-LUAD.normalization.count.tn.xls"
clinic_file = "./results/TCGA-LUAD_clinic.xls"
target_gene = "ENSG00000146648"
output_file = "Summary.xls"
