
download:
    rawCountType: unstranded         # choice unstranded, stranded_first, stranded_second
    normalizationCountType: fpkm_unstranded # choice tpm_unstranded, fpkm_unstranded, fpkm_uq_unstranded
    rawDataDir: /BI2/project/TCGA_public    # put raw files,such as all tcga projects id or raw GDC data
    resultDir: results
    

cancerType: TCGA-LUAD
targetGene: ENSG00000146648    #EGFR

